### ISSUE TITLE
GNOME 40 compatibility

### ISSUE THREAD

**Issue by wooque** [fthx/babar#3] opened 2021-02-05 10:36 UTC
Error in gnome-shell log
```
JS ERROR: TypeError: Main.overview.viewSelector is undefined
_init/<@/home/vuk/.local/share/gnome-shell/extensions/babar@fthx/extension.js:46:66
```
Will try to fix it

**Comment by fthx** [comment] 2021-02-05 11:01
I don't get this one.
I get this one:
```
JS ERROR: TypeError: this.w_box.icon is undefined
_create_window_button@/usr/share/gnome-shell/extensions/babar@fthx/extension.js:220:5
_update_ws@/usr/share/gnome-shell/extensions/babar@fthx/extension.js:187:17

```
that I managed to handle by creating a fallback icon. I already have some surprises creating https://extensions.gnome.org/extension/3915/sticky-terminal/ : the window object may be created but not immediately accessible.

**Comment by fthx** [comment] 2021-02-05 11:11
extension.js is modified in this repo to manage no-icon case, still not in GS ext website.
Do you have a way to reproduce the viewSelector bug? I tried in many ways but did not succeed. :-)
A simple workaround would be to check its existence before calling it, but anyway it's interesting to know why it happens.

**Comment by wooque** [comment] 2021-02-05 11:19
Happens only in GNOME 40, that's why you can't reproduce it. 
Anyway GNOME 40 is still in alpha state so I revert back to 3.38 and will wait until it hits Arch official repos.

**Comment by fthx** [comment] 2021-02-05 13:37
Just FYI:
https://github.com/home-sweet-gnome/dash-to-panel/issues/1265
Same in DtDock too. No hurry, you're right.

**Comment by fthx** [comment] 2021-02-19 17:38
If somebody can test the extension with GNOME 40 these coming weeks, I would be happy to have a feedback. Please check in logs too, searching for keyword "fthx" in "All". Thanks!

**Comment by frandieguez** [comment] 2021-03-08 14:14
I have a couple of computers already in GNOME 40. I can help providing feedback. Do not hesitate to contact me.

**Comment by fthx** [comment] 2021-03-08 14:19
Oh yes it would be interesting to test it some hours and give me your feedback and the result of "fthx" in GNOME Logs ("All" tab).
I think that the app grid button has to be turned off to avoid any error (but not sure of that). Thanks !

@wooque : I have to look longer your PR and I'll merge it soon.

**Comment by frandieguez** [comment] 2021-03-08 20:57
Just point me to the branch and I will test

**Comment by frandieguez** [comment] 2021-03-08 21:01
For now I only get this error.

```
21:57:19 dbus-daemon: [session uid=60399 pid=248293] Activating service name='org.gnome.Shell.Extensions' requested by ':1.105' (uid=60399 pid=258260 comm="gnome-extensions enable babar@fthx ")
21:56:07 gnome-shell: JS ERROR: Could not load extension babar@fthx: Error: Missing metadata.json
createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:283:19
_loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:583:34
collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:27:28
_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:567:19
_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:597:18
_sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:628:18
init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
_initializeUI@resource:///org/gnome/shell/ui/main.js:279:22
start@resource:///org/gnome/shell/ui/main.js:169:5
@<main>:1:47
```

**Comment by fthx** [comment] 2021-03-08 21:21
There is no specific GS 40 branch.
How did you install the extension? Through GitHub or GS website?
Could you check this:
![image](https://user-images.githubusercontent.com/23138504/110383414-82847f00-805c-11eb-962e-7f29b9964ca4.png)
Could you give the content of your metadata.json ?

**Comment by fthx** [comment] 2021-03-08 23:07
Ok I updated my Fedora VM to v34 with GS 40.
Well, that's quite beta.
I confirm that the dconf key was changed when upgrading, you have to set it to true again.

The extension works, at least for the favorites/workspaces/tasks part.
- the folder icon is not displayed
- the appgrid button does not exist anymore
- the prefs UI does not work anymore
I think only this last point will need some work.

**Comment by frandieguez** [comment] 2021-03-08 23:09
Installed via 
`➜ git clone  https://github.com/fthx/babar.git ~/.local/share/gnome-shell/extensions/babar@fthx/
`

Here are the contents

`
➜ cat ~/.local/share/gnome-shell/extensions/babar@fthx/metadata.json                                  
{
  "_generated": "Generated by SweetTooth, do not edit", 
  "description": "Task bar. App grid & favorites & workspaces & tasks in panel. Light extension.\n\n Replace 'Activities' button by all current workspaces and apps buttons. Switch workspace/app or toggle overview by clicking on these buttons. Change 'Places' label to an icon. Some settings in preferences UI.\n\n You can use names for workspaces: there are two ways for that. 1) Edit the string array 'org.gnome.desktop.wm.preferences.workspace-names' gsettings key (through dconf editor, e.g.). 2) Use official GNOME extension Workspaces Indicator's settings. You don't have to write a long enough list: numbers are displayed if no workspace name is defined.\n\n Changelog: https://github.com/fthx/babar/issues/2", 
  "name": "BaBar", 
  "shell-version": ["3.36", "3.38", "3.40", "40.0"], 
  "url": "https://github.com/fthx/babar", 
  "uuid": "babar@fthx", 
  "version": 35
}
`

That key doesn't exist on my machine

**Comment by frandieguez** [comment] 2021-03-08 23:14
Ok, I've done a git pull and now the bar loads

I had to add 40.beta to get the extension to load
  "shell-version": ["3.36", "3.38", "3.40", "40.beta", "40.0"], 

As said, now the top bar loads but the preferences button raises an error.
![image](https://user-images.githubusercontent.com/4584/110394196-4f49ec00-806c-11eb-93a8-dbbe79a54a2d.png)

**Comment by fthx** [comment] 2021-03-08 23:16
Well, I was writing to use "40.beta". Done!
Yes, the prefs UI does not launch (see my previous post). I have to look at the Gtk 4 changes...

**Comment by frandieguez** [comment] 2021-03-08 23:16
Note that gnome-shell 40 forces the usage of GTK4 for extensions dialogs.

**Comment by fthx** [comment] 2021-03-08 23:20
https://developer.gnome.org/gtk4/unstable/gtk-migrating-3-to-4.html#id-1.7.4.3.11

Have to sleep now. ^_^

**Comment by frandieguez** [comment] 2021-03-08 23:45
Check this please

https://github.com/fthx/babar/pull/12

**Comment by fthx** [comment] 2021-03-09 07:56
**TO TESTERS AND DEVS

PLEASE USE:
https://github.com/fthx/babar/tree/GNOME40
FOR GNOME 40 TESTING AND PR**

**Comment by fthx** [comment] 2021-03-13 17:56
Ok, @frandieguez has made the prefs to work in GS 40.
We have to check the extension itself, not clear if it does not make GS 40 buggy.

**Comment by fthx** [comment] 2021-03-13 18:13
I think that the bug happens when pressing Windows key to enter overview.
Unchecking Places-to-icon option seems to remove the crash.

I would be happy if you can report whatever is wrong with GS 40 here!
Thanks again! (and thanks for the margin trick that I did not look, it saved me some time!)

**Comment by fthx** [comment] 2021-03-13 19:46
Ok, in Looking Glass, I reproduced the crash, following the places-to-icon function.
It crashes when I create the folder icon: places_icon = new St.Icon(...)

**Comment by frandieguez** [comment] 2021-03-13 19:57
Let me check with master

**Comment by frandieguez** [comment] 2021-03-13 20:06
![image](https://user-images.githubusercontent.com/4584/111042934-03b68a00-8440-11eb-9314-9959d1266a58.png)
Everything works as expected in GNOME 40.beta

**Comment by frandieguez** [comment] 2021-03-13 20:12
Not sure how to reproduce the bug, but enabling Applications grid, if you click on it it doesnt raises de overview

**Comment by fthx** [comment] 2021-03-13 20:14
Yes, that I know. The app grid command does not exist anymore. Or at least I have to find the new one (I searched this some days ago but failed).

**Comment by fthx** [comment] 2021-03-13 20:15
What system/OS do you use? I do use Fedora 4 VM in Boxes.

**Comment by fthx** [comment] 2021-03-13 20:18
_One question... is it posible to add an option to put favorites alongside open windows? without using a dropdown menu_

I tested this first but it takes a lot of space, too much space.
The way this extension works (list active tasks, 1 icon per task) does not fit this Dash-to-Panel-like behaviour.
But of course it could be an option.

**Comment by frandieguez** [comment] 2021-03-13 21:16
I use archlinux with the fcgu repositoriy to get gnome-unstable https://gitlab.com/fabis_cafe/gnome-unstable

**Comment by frandieguez** [comment] 2021-03-13 21:18
> I tested this first but it takes a lot of space, too much space.
> The way this extension works (list active tasks, 1 icon per task) does not fit this Dash-to-Panel-like behaviour.

Dash to panel has too many options but I like the idea of replicating favorites + running apps in the panel, without loosing the dash in the overview. That would be a great idea for GNOME 40

**Comment by fthx** [comment] 2021-03-14 09:40
Ok, for app grid button I think I found the correct new function, but maybe there's something fishy in GS:
https://gitlab.gnome.org/GNOME/gnome-shell/-/issues/3873

**Comment by fthx** [comment] 2021-03-14 12:08
Ok. Florian Muellner has pushed a fix.
So, virtually, we will be able soon to enter app grid with:
`Main.overview.showApps()`
Just a GS version to check, because this function does not exist in GS < 40.

I'll look at the favorites-as-icons after GS 40 issues are solved.

**Comment by fthx** [comment] 2021-03-14 12:10
Still have to investigate places-to-icon feature.

**Comment by frandieguez** [comment] 2021-03-14 12:12
Thanks for your effort!

**Comment by fthx** [comment] 2021-03-14 14:27
https://github.com/fthx/babar/commit/7a93aa271b57386fada8153eb98edaecfbd22115

What's remaining: Places-to-icon

**Comment by fthx** [comment] 2021-03-14 15:21
Ok, runs fine in GS40 now, places-to-icon included. At least, it seems to. ^_^

@ all: I do not close this thread it until we have used BaBar in GS40 for some time without error.
@frandieguez 

I push it into GS extensions website, as it runs fine in my GS 3.36 too. And it cannot be worse than before in GS 40 ;-) .

**Comment by frandieguez** [comment] 2021-03-14 15:28
Thanks for your work, this is such an achievement

I'm thinking about porting the prefs panel to glade so it is easier to work with. Let me know what you think and I will work on it if you agree.

Maybe using the new libhandy UI

**Comment by fthx** [comment] 2021-03-14 15:40
I don't know much about glade, and I want to fully understand all the parts of the code.
And from now I won't have a lot of time, for some weeks. BUT that's certainly a good idea! I'll can look at any PR when it will be possible. That's not that urgent.

To be honest, if you have some time, I think that the missing key feature is drag'n'drop between workspaces, instead of right-click-arrows workaround. Just drag an icon over a workspace area in panel and then drop it. The order could be the same as now (favorites if choose, then creation time). I don't know if DND has changed during GS40 transition.

Please test BaBar in your GS40 (+ check "fthx" in Logs). Thanks!!

**Comment by fthx** [comment] 2021-03-14 15:43
Oh, and the bug for Places in GS40 was due to drop down arrows removal in GS40. The 'places-menu' object is not the same and there is only one child, not 2 (label + arrow).
Simple but I had to figure out if the problem was simple...

**Comment by frandieguez** [comment] 2021-03-15 22:05
Guide to update extensions https://www.reddit.com/r/gnome/comments/m5hby4/gnome_shell_40_port_guide_part_1_prefsgtk4/

**Comment by fthx** [comment] 2021-03-16 13:18
Thanks!
Text: https://gjs.guide/extensions/upgrading/gnome-shell-40.html

**Comment by fthx** [comment] 2021-03-17 13:37
https://blogs.gnome.org/shell-dev/2021/03/12/gnome-40-your-extension/

**Comment by frandieguez** [comment] 2021-03-29 07:17
Maybe this issue should be closed

**Closed** 2021-03-29 07:18 UTC
Labels: development
